export interface ParticleConfig {
  count: number;
  size: number;
  color: number;
  opacity: number;
  speed: number;         // fall speed
  spread: number;        // horizontal spread
  height: number;        // emitter height
  drift: number;         // horizontal drift factor
  sizeAttenuation: boolean;
  rises?: boolean;       // true = particles float upward (e.g. bubbles)
}

export const WEATHER_CONFIGS: Record<string, ParticleConfig> = {
  snow: {
    count: 12000,
    size: 0.08,
    color: 0xffffff,
    opacity: 0.9,
    speed: 2.0,
    spread: 60,
    height: 30,
    drift: 1.5,
    sizeAttenuation: true,
  },
  rain: {
    count: 10000,
    size: 0.2,
    color: 0xbbccdd,
    opacity: 0.7,
    speed: 16.0,
    spread: 50,
    height: 25,
    drift: 0.4,
    sizeAttenuation: true,
  },
  leaves: {
    count: 2000,
    size: 0.12,
    color: 0xcc6622,
    opacity: 0.85,
    speed: 1.5,
    spread: 60,
    height: 25,
    drift: 3.0,
    sizeAttenuation: true,
  },
  smog: {
    count: 3000,
    size: 0.25,
    color: 0x887766,
    opacity: 0.3,
    speed: 0.5,
    spread: 60,
    height: 20,
    drift: 2.0,
    sizeAttenuation: true,
  },
  ash: {
    count: 2500,
    size: 0.06,
    color: 0x999999,
    opacity: 0.5,
    speed: 1.8,
    spread: 60,
    height: 25,
    drift: 1.0,
    sizeAttenuation: true,
  },
  blizzard: {
    count: 22000,
    size: 0.12,
    color: 0xeeeeff,
    opacity: 0.95,
    speed: 5.5,
    spread: 90,
    height: 40,
    drift: 6.0,
    sizeAttenuation: true,
  },
  drizzle: {
    count: 5000,
    size: 0.15,
    color: 0xaabbcc,
    opacity: 0.5,
    speed: 10.0,
    spread: 60,
    height: 25,
    drift: 0.5,
    sizeAttenuation: true,
  },
  petals: {
    count: 1500,
    size: 0.1,
    color: 0xffbbdd,
    opacity: 0.8,
    speed: 1.0,
    spread: 60,
    height: 20,
    drift: 3.5,
    sizeAttenuation: true,
  },
  hail: {
    count: 8000,
    size: 0.05,
    color: 0xccddee,
    opacity: 0.85,
    speed: 15.0,
    spread: 60,
    height: 30,
    drift: 0.8,
    sizeAttenuation: true,
  },
  storm: {
    count: 14000,
    size: 0.25,
    color: 0xccddee,
    opacity: 0.8,
    speed: 20.0,
    spread: 60,
    height: 25,
    drift: 1.5,
    sizeAttenuation: true,
  },
  frost: {
    count: 3000,
    size: 0.15,
    color: 0xddeeff,
    opacity: 0.6,
    speed: 0.8,
    spread: 60,
    height: 25,
    drift: 1.0,
    sizeAttenuation: true,
  },
  bubbles: {
    count: 2000,
    size: 0.1,
    color: 0x88ddff,
    opacity: 0.5,
    speed: 1.5,
    spread: 50,
    height: 25,
    drift: 2.0,
    sizeAttenuation: true,
    rises: true,
  },
  none: {
    count: 0,
    size: 0.01,
    color: 0x000000,
    opacity: 0,
    speed: 0,
    spread: 0,
    height: 0,
    drift: 0,
    sizeAttenuation: true,
  },
};
