import type { BiomeConfig } from './types';

function rgb(r: number, g: number, b: number) {
  return { r: r / 255, g: g / 255, b: b / 255 };
}

export const BIOME_DEFINITIONS: Record<string, BiomeConfig> = {
  dark_city: {
    name: 'dark_city',
    fogColor: rgb(30, 30, 40),
    fogNear: 8,
    fogFar: 100,
    skyColor: rgb(15, 20, 35),
    skyColorHorizon: rgb(20, 30, 48),
    ambientColor: rgb(40, 50, 70),
    ambientIntensity: 0.3,
    directionalColor: rgb(90, 110, 140),
    directionalIntensity: 0.5,
    groundColor: rgb(50, 50, 55),
    groundColorAlt: rgb(40, 40, 48),
    trackColor: rgb(55, 55, 60),
    floraTypes: ['city_building_small', 'city_building_tall', 'neon_sign'],
    terrainAmplitude: 1.0,
    floraDistribution: {
      near: [
        { model: 'street_lamp_neon', count: 4, scaleMin: 1.5, scaleMax: 2.0 },
        { model: 'shipping_container', count: 2, scaleMin: 1.5, scaleMax: 2.0 },
      ],
      far: [
        { model: 'city_building_small', count: 6, scaleMin: 2.0, scaleMax: 4.0 },
        { model: 'city_building_tall', count: 4, scaleMin: 3.0, scaleMax: 6.0 },
        { model: 'city_skyscraper', count: 2, scaleMin: 4.0, scaleMax: 8.0 },
        { model: 'neon_sign', count: 3, scaleMin: 1.5, scaleMax: 2.5 },
        { model: 'factory_chimney', count: 2, scaleMin: 2.0, scaleMax: 3.5 },
      ],
    },
    distantModels: ['city_skyscraper', 'city_building_tall', 'factory_chimney'],
    weatherType: 'smog',
    weatherIntensity: 0.8,
    windStrength: 0.2,
    isTunnel: false,
    tunnelWallColor: rgb(0, 0, 0),
    hasNeonLights: true,
    neonColors: [0xff00ff, 0x00ffff, 0xff3366, 0x33ff99],
    riverProbability: 0,
    structureDensity: 0.9,
    dayNightInfluence: 0.2,
  },

  industrial: {
    name: 'industrial',
    fogColor: rgb(65, 62, 58),
    fogNear: 15,
    fogFar: 160,
    skyColor: rgb(80, 80, 85),
    skyColorHorizon: rgb(95, 90, 80),
    ambientColor: rgb(100, 90, 75),
    ambientIntensity: 0.4,
    directionalColor: rgb(180, 160, 120),
    directionalIntensity: 0.7,
    groundColor: rgb(65, 60, 50),
    groundColorAlt: rgb(55, 52, 45),
    trackColor: rgb(70, 65, 55),
    floraTypes: ['warehouse', 'factory_building', 'crane'],
    terrainAmplitude: 2.0,
    floraDistribution: {
      near: [
        { model: 'shipping_container', count: 4, scaleMin: 1.5, scaleMax: 2.5 },
        { model: 'storage_tank', count: 2, scaleMin: 2.0, scaleMax: 3.0 },
      ],
      far: [
        { model: 'warehouse', count: 4, scaleMin: 2.5, scaleMax: 4.0 },
        { model: 'factory_building', count: 3, scaleMin: 3.0, scaleMax: 5.0 },
        { model: 'factory_chimney', count: 3, scaleMin: 2.5, scaleMax: 4.5 },
        { model: 'crane', count: 2, scaleMin: 3.0, scaleMax: 5.0 },
        { model: 'storage_tank', count: 3, scaleMin: 2.0, scaleMax: 3.5 },
      ],
    },
    distantModels: ['factory_building', 'factory_chimney', 'crane'],
    weatherType: 'ash',
    weatherIntensity: 0.6,
    windStrength: 0.3,
    isTunnel: false,
    tunnelWallColor: rgb(0, 0, 0),
    hasNeonLights: false,
    neonColors: [],
    riverProbability: 0.05,
    structureDensity: 0.7,
    dayNightInfluence: 0.5,
  },

  suburban: {
    name: 'suburban',
    fogColor: rgb(140, 150, 160),
    fogNear: 25,
    fogFar: 250,
    skyColor: rgb(90, 110, 135),
    skyColorHorizon: rgb(110, 120, 135),
    ambientColor: rgb(150, 160, 170),
    ambientIntensity: 0.6,
    directionalColor: rgb(230, 220, 200),
    directionalIntensity: 0.9,
    groundColor: rgb(70, 85, 55),
    groundColorAlt: rgb(80, 95, 60),
    trackColor: rgb(85, 80, 70),
    floraTypes: ['suburban_house', 'garden_hedge', 'tree_spring'],
    terrainAmplitude: 3.0,
    floraDistribution: {
      near: [
        { model: 'garden_hedge', count: 6, scaleMin: 1.2, scaleMax: 2.0 },
        { model: 'park_bench', count: 3, scaleMin: 1.5, scaleMax: 2.0 },
        { model: 'lamp_post', count: 3, scaleMin: 1.5, scaleMax: 2.0 },
        { model: 'fence_segment', count: 5, scaleMin: 1.5, scaleMax: 2.0 },
      ],
      far: [
        { model: 'suburban_house', count: 5, scaleMin: 2.0, scaleMax: 3.0 },
        { model: 'tree_spring', count: 8, scaleMin: 2.0, scaleMax: 3.5 },
        { model: 'tree_spring_blossom', count: 4, scaleMin: 2.0, scaleMax: 3.0 },
        { model: 'playground', count: 1, scaleMin: 2.0, scaleMax: 2.5 },
        { model: 'garden_hedge', count: 6, scaleMin: 1.5, scaleMax: 2.5 },
        { model: 'bush_spring', count: 8, scaleMin: 1.0, scaleMax: 2.0 },
      ],
    },
    distantModels: ['hill_gentle', 'suburban_house', 'tree_spring', 'hot_air_balloon'],
    weatherType: 'drizzle',
    weatherIntensity: 0.4,
    windStrength: 0.3,
    isTunnel: false,
    tunnelWallColor: rgb(0, 0, 0),
    hasNeonLights: false,
    neonColors: [],
    riverProbability: 0.1,
    structureDensity: 0.5,
    dayNightInfluence: 0.8,
  },

  village: {
    name: 'village',
    fogColor: rgb(150, 140, 120),
    fogNear: 25,
    fogFar: 250,
    skyColor: rgb(100, 120, 150),
    skyColorHorizon: rgb(120, 125, 120),
    ambientColor: rgb(170, 155, 130),
    ambientIntensity: 0.6,
    directionalColor: rgb(255, 220, 170),
    directionalIntensity: 1.1,
    groundColor: rgb(95, 80, 50),
    groundColorAlt: rgb(85, 75, 45),
    trackColor: rgb(90, 75, 55),
    floraTypes: ['barn', 'hay_bale', 'oak_autumn'],
    terrainAmplitude: 4.0,
    floraDistribution: {
      near: [
        { model: 'hay_bale', count: 5, scaleMin: 1.2, scaleMax: 2.0 },
        { model: 'fence_segment', count: 6, scaleMin: 1.5, scaleMax: 2.0 },
        { model: 'well', count: 1, scaleMin: 1.5, scaleMax: 2.0 },
        { model: 'farm_field', count: 3, scaleMin: 2.0, scaleMax: 3.0 },
      ],
      far: [
        { model: 'barn', count: 2, scaleMin: 2.5, scaleMax: 3.5 },
        { model: 'house_small', count: 3, scaleMin: 2.0, scaleMax: 2.8 },
        { model: 'windmill', count: 1, scaleMin: 2.5, scaleMax: 3.5 },
        { model: 'mosque', count: 1, scaleMin: 2.5, scaleMax: 3.0 },
        { model: 'oak_autumn', count: 6, scaleMin: 2.0, scaleMax: 3.5 },
        { model: 'oak_autumn_large', count: 3, scaleMin: 2.5, scaleMax: 4.5 },
        { model: 'hay_bale', count: 4, scaleMin: 1.5, scaleMax: 2.5 },
        { model: 'undergrowth_autumn', count: 10, scaleMin: 2.0, scaleMax: 3.5 },
      ],
    },
    distantModels: ['mountain_autumn', 'mosque', 'windmill', 'barn', 'hot_air_balloon'],
    weatherType: 'leaves',
    weatherIntensity: 0.5,
    windStrength: 0.4,
    isTunnel: false,
    tunnelWallColor: rgb(0, 0, 0),
    hasNeonLights: false,
    neonColors: [],
    riverProbability: 0.15,
    structureDensity: 0.4,
    dayNightInfluence: 0.9,
  },

  wilderness: {
    name: 'wilderness',
    fogColor: rgb(100, 120, 100),
    fogNear: 20,
    fogFar: 180,
    skyColor: rgb(70, 105, 145),
    skyColorHorizon: rgb(95, 115, 130),
    ambientColor: rgb(120, 150, 120),
    ambientIntensity: 0.7,
    directionalColor: rgb(255, 240, 200),
    directionalIntensity: 1.0,
    groundColor: rgb(55, 80, 40),
    groundColorAlt: rgb(65, 90, 48),
    trackColor: rgb(80, 70, 50),
    floraTypes: ['pine_snow', 'rock_mossy', 'bush_spring'],
    terrainAmplitude: 5.0,
    floraDistribution: {
      near: [
        { model: 'pine_snow', count: 6, scaleMin: 2.0, scaleMax: 3.5 },
        { model: 'rock_mossy', count: 4, scaleMin: 1.0, scaleMax: 2.0 },
        { model: 'bush_spring', count: 6, scaleMin: 1.0, scaleMax: 2.0 },
        { model: 'undergrowth_spring', count: 10, scaleMin: 1.5, scaleMax: 3.0 },
      ],
      far: [
        { model: 'pine_snow_tall', count: 12, scaleMin: 2.5, scaleMax: 5.0 },
        { model: 'pine_snow', count: 10, scaleMin: 2.0, scaleMax: 4.0 },
        { model: 'tree_spring', count: 6, scaleMin: 2.5, scaleMax: 4.0 },
        { model: 'willow_spring', count: 3, scaleMin: 3.0, scaleMax: 4.5 },
        { model: 'boulder_mossy', count: 4, scaleMin: 1.5, scaleMax: 3.0 },
        { model: 'rock_cluster', count: 3, scaleMin: 1.5, scaleMax: 2.5 },
        { model: 'undergrowth_spring', count: 14, scaleMin: 2.0, scaleMax: 4.0 },
        { model: 'undergrowth_snow', count: 8, scaleMin: 2.0, scaleMax: 3.5 },
      ],
    },
    distantModels: ['mountain_snow', 'hill_gentle', 'pine_snow_tall'],
    weatherType: 'snow',
    weatherIntensity: 0.8,
    windStrength: 0.3,
    isTunnel: false,
    tunnelWallColor: rgb(0, 0, 0),
    hasNeonLights: false,
    neonColors: [],
    riverProbability: 0.3,
    structureDensity: 0.1,
    dayNightInfluence: 1.0,
  },

  tunnel: {
    name: 'tunnel',
    fogColor: rgb(10, 10, 12),
    fogNear: 3,
    fogFar: 40,
    skyColor: rgb(5, 5, 8),
    skyColorHorizon: rgb(8, 8, 12),
    ambientColor: rgb(30, 28, 25),
    ambientIntensity: 0.2,
    directionalColor: rgb(80, 70, 50),
    directionalIntensity: 0.2,
    groundColor: rgb(35, 32, 30),
    groundColorAlt: rgb(30, 28, 26),
    trackColor: rgb(50, 48, 45),
    floraTypes: [],
    terrainAmplitude: 0.5,
    floraDistribution: {
      near: [
        { model: 'tunnel_light', count: 4, scaleMin: 1.0, scaleMax: 1.5 },
        { model: 'pipe_segment', count: 3, scaleMin: 1.5, scaleMax: 2.5 },
      ],
      far: [
        { model: 'tunnel_support', count: 4, scaleMin: 2.0, scaleMax: 3.0 },
        { model: 'underground_structure', count: 2, scaleMin: 2.0, scaleMax: 3.5 },
        { model: 'pipe_segment', count: 4, scaleMin: 1.5, scaleMax: 3.0 },
        { model: 'icicle_cluster', count: 5, scaleMin: 1.5, scaleMax: 3.0 },
      ],
    },
    distantModels: [],
    weatherType: 'none',
    weatherIntensity: 0,
    windStrength: 0,
    isTunnel: true,
    tunnelWallColor: rgb(40, 38, 35),
    hasNeonLights: false,
    neonColors: [],
    riverProbability: 0,
    structureDensity: 0.3,
    dayNightInfluence: 0,
  },

  polar: {
    name: 'polar',
    fogColor: rgb(140, 150, 165),
    fogNear: 15,
    fogFar: 150,
    skyColor: rgb(70, 80, 105),
    skyColorHorizon: rgb(95, 105, 125),
    ambientColor: rgb(130, 140, 160),
    ambientIntensity: 0.4,
    directionalColor: rgb(160, 170, 190),
    directionalIntensity: 0.4,
    groundColor: rgb(220, 230, 240),
    groundColorAlt: rgb(200, 215, 230),
    trackColor: rgb(180, 185, 195),
    floraTypes: ['frozen_pine', 'ice_crystal', 'polar_rock'],
    terrainAmplitude: 2.5,
    floraDistribution: {
      near: [
        { model: 'ice_crystal', count: 5, scaleMin: 1.5, scaleMax: 3.0 },
        { model: 'polar_rock', count: 4, scaleMin: 1.0, scaleMax: 2.5 },
        { model: 'snow_drift', count: 6, scaleMin: 1.5, scaleMax: 3.0 },
        { model: 'icicle_cluster', count: 4, scaleMin: 1.0, scaleMax: 2.0 },
      ],
      far: [
        { model: 'frozen_pine', count: 8, scaleMin: 2.0, scaleMax: 4.0 },
        { model: 'ice_pillar', count: 4, scaleMin: 2.5, scaleMax: 5.0 },
        { model: 'igloo', count: 2, scaleMin: 2.0, scaleMax: 3.0 },
        { model: 'ice_crystal', count: 6, scaleMin: 2.0, scaleMax: 4.0 },
        { model: 'snow_drift', count: 10, scaleMin: 2.0, scaleMax: 4.0 },
        { model: 'aurora_pole', count: 3, scaleMin: 2.0, scaleMax: 3.5 },
      ],
    },
    distantModels: ['mountain_ice', 'ice_pillar', 'frozen_pine'],
    weatherType: 'blizzard',
    weatherIntensity: 1.0,
    windStrength: 0.9,
    isTunnel: false,
    tunnelWallColor: rgb(0, 0, 0),
    hasNeonLights: false,
    neonColors: [],
    riverProbability: 0.05,
    structureDensity: 0.1,
    dayNightInfluence: 1.0,
  },

  autumn_forest: {
    name: 'autumn_forest',
    fogColor: rgb(130, 110, 80),
    fogNear: 20,
    fogFar: 200,
    skyColor: rgb(85, 95, 120),
    skyColorHorizon: rgb(110, 100, 80),
    ambientColor: rgb(150, 130, 100),
    ambientIntensity: 0.6,
    directionalColor: rgb(240, 200, 140),
    directionalIntensity: 1.1,
    groundColor: rgb(80, 60, 35),
    groundColorAlt: rgb(90, 70, 40),
    trackColor: rgb(85, 70, 50),
    floraTypes: ['oak_autumn', 'maple_autumn', 'birch_autumn'],
    terrainAmplitude: 5.0,
    floraDistribution: {
      near: [
        { model: 'mushroom_cluster', count: 6, scaleMin: 1.0, scaleMax: 2.0 },
        { model: 'log_pile', count: 3, scaleMin: 1.5, scaleMax: 2.5 },
        { model: 'undergrowth_autumn', count: 10, scaleMin: 1.5, scaleMax: 3.0 },
        { model: 'rock_mossy', count: 4, scaleMin: 1.0, scaleMax: 2.0 },
      ],
      far: [
        { model: 'oak_autumn', count: 10, scaleMin: 2.5, scaleMax: 4.5 },
        { model: 'oak_autumn_large', count: 5, scaleMin: 3.0, scaleMax: 5.0 },
        { model: 'maple_autumn', count: 8, scaleMin: 2.5, scaleMax: 4.0 },
        { model: 'birch_autumn', count: 6, scaleMin: 2.0, scaleMax: 4.0 },
        { model: 'undergrowth_autumn', count: 14, scaleMin: 2.0, scaleMax: 4.0 },
        { model: 'boulder_mossy', count: 3, scaleMin: 1.5, scaleMax: 3.0 },
      ],
    },
    distantModels: ['mountain_autumn', 'oak_autumn_large', 'hill_gentle'],
    weatherType: 'leaves',
    weatherIntensity: 0.7,
    windStrength: 0.5,
    isTunnel: false,
    tunnelWallColor: rgb(0, 0, 0),
    hasNeonLights: false,
    neonColors: [],
    riverProbability: 0.25,
    structureDensity: 0.15,
    dayNightInfluence: 1.0,
  },

  spring_meadow: {
    name: 'spring_meadow',
    fogColor: rgb(120, 125, 135),
    fogNear: 15,
    fogFar: 180,
    skyColor: rgb(90, 95, 110),
    skyColorHorizon: rgb(120, 125, 138),
    ambientColor: rgb(120, 125, 135),
    ambientIntensity: 0.45,
    directionalColor: rgb(160, 160, 158),
    directionalIntensity: 0.4,
    groundColor: rgb(70, 110, 45),
    groundColorAlt: rgb(80, 120, 55),
    trackColor: rgb(80, 75, 55),
    floraTypes: ['tree_spring', 'tree_spring_blossom', 'bush_spring'],
    terrainAmplitude: 3.5,
    floraDistribution: {
      near: [
        { model: 'wildflower_patch', count: 10, scaleMin: 1.5, scaleMax: 3.0 },
        { model: 'bush_spring', count: 6, scaleMin: 1.2, scaleMax: 2.0 },
        { model: 'beehive', count: 2, scaleMin: 1.5, scaleMax: 2.5 },
        { model: 'fence_segment', count: 4, scaleMin: 1.5, scaleMax: 2.0 },
        { model: 'undergrowth_spring', count: 8, scaleMin: 1.5, scaleMax: 3.0 },
      ],
      far: [
        { model: 'tree_spring', count: 10, scaleMin: 2.5, scaleMax: 4.5 },
        { model: 'tree_spring_blossom', count: 8, scaleMin: 2.0, scaleMax: 4.0 },
        { model: 'willow_spring', count: 4, scaleMin: 3.0, scaleMax: 5.0 },
        { model: 'cottage', count: 3, scaleMin: 2.0, scaleMax: 3.0 },
        { model: 'stream_bridge', count: 2, scaleMin: 2.0, scaleMax: 3.0 },
        { model: 'wildflower_patch', count: 12, scaleMin: 2.0, scaleMax: 4.0 },
      ],
    },
    distantModels: ['hill_gentle', 'cottage', 'tree_spring_blossom', 'hot_air_balloon'],
    weatherType: 'rain',
    weatherIntensity: 0.8,
    windStrength: 0.4,
    isTunnel: false,
    tunnelWallColor: rgb(0, 0, 0),
    hasNeonLights: false,
    neonColors: [],
    riverProbability: 0.3,
    structureDensity: 0.3,
    dayNightInfluence: 1.0,
  },

  arctic_coast: {
    name: 'arctic_coast',
    fogColor: rgb(120, 135, 155),
    fogNear: 12,
    fogFar: 130,
    skyColor: rgb(60, 72, 100),
    skyColorHorizon: rgb(80, 95, 115),
    ambientColor: rgb(110, 125, 150),
    ambientIntensity: 0.4,
    directionalColor: rgb(160, 170, 190),
    directionalIntensity: 0.4,
    groundColor: rgb(170, 185, 200),
    groundColorAlt: rgb(150, 170, 190),
    trackColor: rgb(155, 160, 170),
    floraTypes: ['ice_berg', 'frozen_wreck', 'polar_rock'],
    terrainAmplitude: 2.0,
    floraDistribution: {
      near: [
        { model: 'ice_crystal', count: 4, scaleMin: 1.0, scaleMax: 2.5 },
        { model: 'polar_rock', count: 4, scaleMin: 1.0, scaleMax: 2.0 },
        { model: 'snow_drift', count: 5, scaleMin: 1.5, scaleMax: 3.0 },
      ],
      far: [
        { model: 'ice_berg', count: 4, scaleMin: 2.5, scaleMax: 5.0 },
        { model: 'frozen_wreck', count: 2, scaleMin: 2.0, scaleMax: 3.5 },
        { model: 'frozen_pine', count: 5, scaleMin: 2.0, scaleMax: 3.5 },
        { model: 'ice_pillar', count: 3, scaleMin: 2.5, scaleMax: 4.5 },
        { model: 'aurora_pole', count: 3, scaleMin: 2.0, scaleMax: 3.0 },
        { model: 'snow_drift', count: 8, scaleMin: 2.0, scaleMax: 4.0 },
      ],
    },
    distantModels: ['mountain_ice', 'ice_berg', 'frozen_pine'],
    weatherType: 'blizzard',
    weatherIntensity: 0.95,
    windStrength: 0.8,
    isTunnel: false,
    tunnelWallColor: rgb(0, 0, 0),
    hasNeonLights: false,
    neonColors: [],
    riverProbability: 0.4,
    structureDensity: 0.1,
    dayNightInfluence: 1.0,
  },

  construction: {
    name: 'construction',
    fogColor: rgb(120, 115, 100),
    fogNear: 20,
    fogFar: 200,
    skyColor: rgb(95, 100, 115),
    skyColorHorizon: rgb(110, 108, 100),
    ambientColor: rgb(140, 130, 110),
    ambientIntensity: 0.5,
    directionalColor: rgb(220, 200, 160),
    directionalIntensity: 0.8,
    groundColor: rgb(100, 85, 60),
    groundColorAlt: rgb(90, 78, 55),
    trackColor: rgb(90, 80, 65),
    floraTypes: ['construction_scaffold', 'crane', 'construction_site'],
    terrainAmplitude: 2.5,
    floraDistribution: {
      near: [
        { model: 'construction_scaffold', count: 4, scaleMin: 1.5, scaleMax: 2.5 },
        { model: 'shipping_container', count: 3, scaleMin: 1.5, scaleMax: 2.5 },
        { model: 'construction_site', count: 2, scaleMin: 2.0, scaleMax: 3.0 },
      ],
      far: [
        { model: 'crane', count: 3, scaleMin: 3.0, scaleMax: 5.0 },
        { model: 'warehouse', count: 3, scaleMin: 2.5, scaleMax: 4.0 },
        { model: 'house_small', count: 3, scaleMin: 2.0, scaleMax: 3.0 },
        { model: 'construction_scaffold', count: 4, scaleMin: 2.0, scaleMax: 3.5 },
        { model: 'factory_chimney', count: 2, scaleMin: 2.0, scaleMax: 3.5 },
      ],
    },
    distantModels: ['crane', 'factory_building', 'city_building_tall'],
    weatherType: 'drizzle',
    weatherIntensity: 0.4,
    windStrength: 0.3,
    isTunnel: false,
    tunnelWallColor: rgb(0, 0, 0),
    hasNeonLights: false,
    neonColors: [],
    riverProbability: 0.05,
    structureDensity: 0.7,
    dayNightInfluence: 0.6,
  },
  ocean: {
    name: 'ocean',
    fogColor: rgb(65, 75, 85),
    fogNear: 15,
    fogFar: 120,
    skyColor: rgb(45, 50, 60),
    skyColorHorizon: rgb(60, 68, 78),
    ambientColor: rgb(55, 65, 80),
    ambientIntensity: 0.35,
    directionalColor: rgb(100, 110, 125),
    directionalIntensity: 0.3,
    groundColor: rgb(55, 90, 100),
    groundColorAlt: rgb(45, 80, 95),
    trackColor: rgb(75, 85, 95),
    floraTypes: ['lighthouse', 'buoy', 'pier_post'],
    terrainAmplitude: 0.2,
    floraDistribution: {
      near: [
        { model: 'pier_post', count: 6, scaleMin: 1.5, scaleMax: 2.5 },
        { model: 'buoy', count: 4, scaleMin: 1.0, scaleMax: 2.0 },
        { model: 'barrel', count: 3, scaleMin: 1.0, scaleMax: 1.5 },
      ],
      far: [
        { model: 'lighthouse', count: 2, scaleMin: 3.0, scaleMax: 5.0 },
        { model: 'fishing_boat', count: 3, scaleMin: 2.0, scaleMax: 3.5 },
        { model: 'sea_rock', count: 5, scaleMin: 1.5, scaleMax: 3.0 },
        { model: 'pier_post', count: 8, scaleMin: 2.0, scaleMax: 3.0 },
        { model: 'seagull_perch', count: 4, scaleMin: 1.5, scaleMax: 2.5 },
      ],
    },
    distantModels: ['lighthouse', 'fishing_boat', 'sea_rock'],
    weatherType: 'storm',
    weatherIntensity: 1.0,
    windStrength: 0.9,
    isTunnel: false,
    tunnelWallColor: rgb(0, 0, 0),
    hasNeonLights: false,
    neonColors: [],
    riverProbability: 0,
    structureDensity: 0.2,
    dayNightInfluence: 0.3,
  },

  frozen_waste: {
    name: 'frozen_waste',
    fogColor: rgb(150, 160, 175),
    fogNear: 12,
    fogFar: 130,
    skyColor: rgb(75, 85, 110),
    skyColorHorizon: rgb(100, 110, 130),
    ambientColor: rgb(140, 150, 170),
    ambientIntensity: 0.4,
    directionalColor: rgb(160, 170, 190),
    directionalIntensity: 0.4,
    groundColor: rgb(240, 245, 250),
    groundColorAlt: rgb(230, 238, 245),
    trackColor: rgb(210, 215, 225),
    floraTypes: ['frost_crystal_large', 'snow_covered_tree', 'frozen_lake_slab'],
    terrainAmplitude: 2.0,
    floraDistribution: {
      near: [
        { model: 'frost_crystal_large', count: 5, scaleMin: 1.5, scaleMax: 3.0 },
        { model: 'snow_drift', count: 6, scaleMin: 1.5, scaleMax: 3.0 },
        { model: 'frozen_lake_slab', count: 3, scaleMin: 2.0, scaleMax: 3.5 },
        { model: 'icicle_cluster', count: 4, scaleMin: 1.0, scaleMax: 2.0 },
      ],
      far: [
        { model: 'snow_covered_tree', count: 8, scaleMin: 2.0, scaleMax: 4.0 },
        { model: 'snow_wall', count: 4, scaleMin: 2.0, scaleMax: 3.5 },
        { model: 'ice_pillar', count: 4, scaleMin: 2.5, scaleMax: 5.0 },
        { model: 'igloo', count: 2, scaleMin: 2.0, scaleMax: 3.0 },
        { model: 'ice_crystal', count: 6, scaleMin: 2.0, scaleMax: 4.0 },
        { model: 'snow_drift', count: 10, scaleMin: 2.0, scaleMax: 4.0 },
      ],
    },
    distantModels: ['mountain_ice', 'ice_pillar', 'snow_covered_tree'],
    weatherType: 'blizzard',
    weatherIntensity: 1.0,
    windStrength: 0.6,
    isTunnel: false,
    tunnelWallColor: rgb(0, 0, 0),
    hasNeonLights: false,
    neonColors: [],
    riverProbability: 0,
    structureDensity: 0.1,
    dayNightInfluence: 1.0,
  },

  amazon: {
    name: 'amazon',
    fogColor: rgb(50, 70, 45),
    fogNear: 5,
    fogFar: 80,
    skyColor: rgb(40, 50, 55),
    skyColorHorizon: rgb(55, 65, 55),
    ambientColor: rgb(50, 70, 45),
    ambientIntensity: 0.35,
    directionalColor: rgb(80, 100, 70),
    directionalIntensity: 0.3,
    groundColor: rgb(35, 55, 25),
    groundColorAlt: rgb(40, 60, 30),
    trackColor: rgb(60, 55, 40),
    floraTypes: ['jungle_tree', 'jungle_vine', 'giant_leaf'],
    terrainAmplitude: 3.0,
    floraDistribution: {
      near: [
        { model: 'jungle_vine', count: 8, scaleMin: 2.0, scaleMax: 4.0 },
        { model: 'giant_leaf', count: 6, scaleMin: 1.5, scaleMax: 3.0 },
        { model: 'jungle_fern', count: 10, scaleMin: 1.5, scaleMax: 3.0 },
        { model: 'jungle_mushroom', count: 4, scaleMin: 1.0, scaleMax: 2.0 },
      ],
      far: [
        { model: 'jungle_tree', count: 14, scaleMin: 3.0, scaleMax: 6.0 },
        { model: 'jungle_tree_tall', count: 8, scaleMin: 4.0, scaleMax: 8.0 },
        { model: 'jungle_vine', count: 10, scaleMin: 2.5, scaleMax: 5.0 },
        { model: 'giant_leaf', count: 8, scaleMin: 2.0, scaleMax: 4.0 },
        { model: 'jungle_fern', count: 12, scaleMin: 2.0, scaleMax: 4.0 },
        { model: 'jungle_ruins', count: 2, scaleMin: 2.5, scaleMax: 4.0 },
      ],
    },
    distantModels: ['jungle_tree_tall', 'jungle_tree', 'hill_gentle'],
    weatherType: 'storm',
    weatherIntensity: 1.0,
    windStrength: 0.7,
    isTunnel: false,
    tunnelWallColor: rgb(0, 0, 0),
    hasNeonLights: false,
    neonColors: [],
    riverProbability: 0.4,
    structureDensity: 0.1,
    dayNightInfluence: 0.5,
  },

  thunderstorm: {
    name: 'thunderstorm',
    fogColor: rgb(60, 65, 70),
    fogNear: 5,
    fogFar: 60,
    skyColor: rgb(40, 45, 55),
    skyColorHorizon: rgb(65, 65, 72),
    ambientColor: rgb(55, 60, 70),
    ambientIntensity: 0.25,
    directionalColor: rgb(80, 85, 100),
    directionalIntensity: 0.2,
    groundColor: rgb(55, 50, 40),
    groundColorAlt: rgb(50, 45, 38),
    trackColor: rgb(60, 55, 48),
    floraTypes: ['fallen_tree', 'storm_debris', 'rock_mossy'],
    terrainAmplitude: 4.0,
    floraDistribution: {
      near: [
        { model: 'fallen_tree', count: 3, scaleMin: 1.5, scaleMax: 2.5 },
        { model: 'storm_debris', count: 4, scaleMin: 1.5, scaleMax: 3.0 },
        { model: 'rock_mossy', count: 4, scaleMin: 1.0, scaleMax: 2.0 },
        { model: 'undergrowth_autumn', count: 8, scaleMin: 1.5, scaleMax: 3.0 },
      ],
      far: [
        { model: 'oak_autumn', count: 6, scaleMin: 2.5, scaleMax: 4.5 },
        { model: 'pine_snow_tall', count: 6, scaleMin: 2.5, scaleMax: 5.0 },
        { model: 'dead_shrub', count: 5, scaleMin: 1.5, scaleMax: 3.0 },
        { model: 'fallen_tree', count: 3, scaleMin: 2.0, scaleMax: 3.5 },
        { model: 'boulder_mossy', count: 4, scaleMin: 1.5, scaleMax: 3.0 },
      ],
    },
    distantModels: ['mountain_autumn', 'hill_gentle', 'oak_autumn_large'],
    weatherType: 'rain',
    weatherIntensity: 1.0,
    windStrength: 0.8,
    isTunnel: false,
    tunnelWallColor: rgb(0, 0, 0),
    hasNeonLights: false,
    neonColors: [],
    riverProbability: 0.1,
    structureDensity: 0.2,
    dayNightInfluence: 0.3,
  },

  cave: {
    name: 'cave',
    fogColor: rgb(15, 12, 10),
    fogNear: 3,
    fogFar: 50,
    skyColor: rgb(8, 6, 5),
    skyColorHorizon: rgb(12, 10, 8),
    ambientColor: rgb(25, 20, 15),
    ambientIntensity: 0.15,
    directionalColor: rgb(60, 50, 35),
    directionalIntensity: 0.15,
    groundColor: rgb(45, 38, 30),
    groundColorAlt: rgb(38, 32, 25),
    trackColor: rgb(50, 45, 38),
    floraTypes: ['stalactite', 'stalagmite', 'cave_crystal'],
    terrainAmplitude: 1.0,
    floraDistribution: {
      near: [
        { model: 'stalactite', count: 8, scaleMin: 1.5, scaleMax: 3.5 },
        { model: 'stalagmite', count: 6, scaleMin: 1.5, scaleMax: 3.0 },
        { model: 'cave_puddle', count: 4, scaleMin: 1.5, scaleMax: 3.0 },
        { model: 'cave_crystal', count: 3, scaleMin: 1.0, scaleMax: 2.0 },
      ],
      far: [
        { model: 'stalactite', count: 10, scaleMin: 2.0, scaleMax: 5.0 },
        { model: 'stalagmite', count: 8, scaleMin: 2.0, scaleMax: 4.0 },
        { model: 'cave_pillar', count: 4, scaleMin: 3.0, scaleMax: 6.0 },
        { model: 'cave_crystal', count: 5, scaleMin: 2.0, scaleMax: 4.0 },
        { model: 'cave_puddle', count: 6, scaleMin: 2.0, scaleMax: 4.0 },
        { model: 'cave_mushroom', count: 4, scaleMin: 1.5, scaleMax: 3.0 },
      ],
    },
    distantModels: ['cave_pillar', 'stalactite', 'cave_crystal'],
    weatherType: 'drizzle',
    weatherIntensity: 0.2,
    windStrength: 0,
    isTunnel: true,
    tunnelWallColor: rgb(35, 30, 22),
    hasNeonLights: false,
    neonColors: [],
    riverProbability: 0.3,
    structureDensity: 0.3,
    dayNightInfluence: 0,
  },
};

export const BIOME_ORDER = [
  'spring_meadow',
  'village',
  'autumn_forest',
  'amazon',
  'thunderstorm',
  'suburban',
  'ocean',
  'wilderness',
  'cave',
  'tunnel',
  'industrial',
  'construction',
  'dark_city',
  'frozen_waste',
  'polar',
  'arctic_coast',
];
